services:
  - type: web
    name: quiz-macro
    runtime: static
    buildCommand: ""
    staticPublishPath: .
    pullRequestPreviewsEnabled: false
    headers:
      - path: /*
        name: Cache-Control
        value: public, max-age=0, must-revalidate
      - path: /*
        name: X-Content-Type-Options
        value: nosniff
